.TH "/home/runner/work/Raytracer/Raytracer/src/Plugins Directory Reference" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Plugins Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEntities\fP"
.br
.ti -1c
.RI "directory \fBFilters\fP"
.br
.ti -1c
.RI "directory \fBMaterials\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApi\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPluginHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPluginLoader\&.hpp\fP"
.br
.in -1c
