.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/TransparencyMaterial Directory Reference" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/TransparencyMaterial Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTransparencyCreator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTransparencyMaterial\&.hpp\fP"
.br
.in -1c
