.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/SpotLight Directory Reference" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/SpotLight Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSpotLightCreator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSpotLightEntity\&.hpp\fP"
.br
.in -1c
