.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt Directory Reference" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAmbientLight\fP"
.br
.ti -1c
.RI "directory \fBAntiAliasing\fP"
.br
.ti -1c
.RI "directory \fBBlackAndWhite\fP"
.br
.ti -1c
.RI "directory \fBCamera\fP"
.br
.ti -1c
.RI "directory \fBChessBoardMaterial\fP"
.br
.ti -1c
.RI "directory \fBCone\fP"
.br
.ti -1c
.RI "directory \fBCylinder\fP"
.br
.ti -1c
.RI "directory \fBDisk\fP"
.br
.ti -1c
.RI "directory \fBLimitedCone\fP"
.br
.ti -1c
.RI "directory \fBLimitedCylinder\fP"
.br
.ti -1c
.RI "directory \fBLimitedPlane\fP"
.br
.ti -1c
.RI "directory \fBMirrorMaterial\fP"
.br
.ti -1c
.RI "directory \fBObj\fP"
.br
.ti -1c
.RI "directory \fBPlainMaterial\fP"
.br
.ti -1c
.RI "directory \fBPlane\fP"
.br
.ti -1c
.RI "directory \fBPointLight\fP"
.br
.ti -1c
.RI "directory \fBRefractionMaterial\fP"
.br
.ti -1c
.RI "directory \fBSphere\fP"
.br
.ti -1c
.RI "directory \fBSpotLight\fP"
.br
.ti -1c
.RI "directory \fBTorus\fP"
.br
.ti -1c
.RI "directory \fBTransparencyMaterial\fP"
.br
.ti -1c
.RI "directory \fBTriangle\fP"
.br
.ti -1c
.RI "directory \fBZebraMaterial\fP"
.br
.in -1c
