.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/ChessBoardMaterial Directory Reference" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/ChessBoardMaterial Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBChessBoardCreator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBChessBoardMaterial\&.hpp\fP"
.br
.in -1c
