.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/PlainMaterial Directory Reference" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/PlainMaterial Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPlainMaterial\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPlainMaterialCreator\&.hpp\fP"
.br
.in -1c
