.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/Plane Directory Reference" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/Plane Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPlaneCreator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPlaneEntity\&.hpp\fP"
.br
.in -1c
