.TH "/home/runner/work/Raytracer/Raytracer/src/Entities Directory Reference" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBTransform\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBICamera\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIEntity\&.hpp\fP"
.br
.ti -1c
.RI "file \fBILight\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIMaterial\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIPrimitive\&.hpp\fP"
.br
.in -1c
