.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/Transform Directory Reference" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/Transform Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBITransform\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTransform\&.hpp\fP"
.br
.ti -1c
.RI "file \fBVector2i\&.hpp\fP"
.br
.ti -1c
.RI "file \fBVector3f\&.hpp\fP"
.br
.in -1c
