.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/Cone Directory Reference" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/Cone Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConeCreator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBConeEntity\&.hpp\fP"
.br
.in -1c
