.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/LimitedPlane Directory Reference" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/LimitedPlane Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLimitedPlaneCreator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLimitedPlaneEntity\&.hpp\fP"
.br
.in -1c
