.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/Camera/Cluster/CameraClusterEntity.hpp" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/Camera/Cluster/CameraClusterEntity.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <optional>\fP
.br
\fC#include 'ICamera\&.hpp'\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'ISceneState\&.hpp'\fP
.br
\fC#include 'IDisplayable\&.hpp'\fP
.br
\fC#include 'Transform\&.hpp'\fP
.br
\fC#include 'Vector2i\&.hpp'\fP
.br
\fC#include 'Vector3f\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::PluginsExt::Camera::Clustered::CameraClusterEntity\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::Camera\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::Camera::Clustered\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
