.TH "/home/runner/work/Raytracer/Raytracer/src/Display/Modules/CanvasModule.hpp" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Display/Modules/CanvasModule.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics/Font\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Image\&.hpp>\fP
.br
\fC#include <SFML/System/Clock\&.hpp>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'ICamera\&.hpp'\fP
.br
\fC#include 'IDisplayModule\&.hpp'\fP
.br
\fC#include 'ITransform\&.hpp'\fP
.br
\fC#include 'Scene\&.hpp'\fP
.br
\fC#include 'Transform\&.hpp'\fP
.br
\fC#include 'Vector3f\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Display::CanvasModule\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Display\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
