.TH "/home/runner/work/Raytracer/Raytracer/src/Images/Color.hpp" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Images/Color.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <mutex>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <SFML/Graphics/Color\&.hpp>\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Images::Color\fP"
.br
.RI "The \fBColor\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Images\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBRayTracer::Images::Color\fP &color)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBRayTracer::Images::Color\fP & color)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
