.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/Camera/FullCustom/CustomRayIterator.hpp" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/Camera/FullCustom/CustomRayIterator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'ICamera\&.hpp'\fP
.br
\fC#include 'IRayIterator\&.hpp'\fP
.br
\fC#include 'Ray\&.hpp'\fP
.br
\fC#include 'Vector2i\&.hpp'\fP
.br
\fC#include 'Vector3f\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::PluginsExt::Camera::FullCustom::CustomRayIterator\fP"
.br
.RI "The \fBCustomRayIterator\fP class\&. "
.ti -1c
.RI "class \fBRayTracer::PluginsExt::Camera::FullCustom::CustomRayIterator::Iterator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::Camera\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::Camera::FullCustom\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
