.TH "/home/runner/work/Raytracer/Raytracer/src/Scenes/Displayable.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Scenes/Displayable.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'IDisplayable\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Scenes::Displayable\fP"
.br
.RI "The \fBDisplayable\fP class\&. "
.ti -1c
.RI "class \fBRayTracer::Scenes::Displayable::DisplayableException\fP"
.br
.RI "an exception for when the key is not found "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.ti -1c
.RI " \fBRayTracer::Scenes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
