.TH "/home/runner/work/Raytracer/Raytracer/src/Plugins/Entities/EntityLoader.hpp" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Plugins/Entities/EntityLoader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'TFactory\&.hpp'\fP
.br
\fC#include 'IEntity\&.hpp'\fP
.br
\fC#include 'PluginLoader\&.hpp'\fP
.br
\fC#include 'EntityHandler\&.hpp'\fP
.br
\fC#include 'EntityFactory\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Plugins::Entities::EntityLoader\fP"
.br
.RI "The \fBEntityLoader\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins::Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
