.TH "/home/runner/work/Raytracer/Raytracer/src/Factories/EntityFactory.hpp" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Factories/EntityFactory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IEntityFactory\&.hpp'\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'TFactory\&.hpp'\fP
.br
\fC#include 'EntityHandler\&.hpp'\fP
.br
\fC#include 'IEntity\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Factories::EntityFactory\fP"
.br
.RI "The \fBEntityFactory\fP (singleton factory) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Factories\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
