.TH "/home/runner/work/Raytracer/Raytracer/src/Plugins/Filters/FilterLoader.hpp" 1 "Wed May 10 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Plugins/Filters/FilterLoader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'TFactory\&.hpp'\fP
.br
\fC#include 'IFilter\&.hpp'\fP
.br
\fC#include 'FilterHandler\&.hpp'\fP
.br
\fC#include 'PluginLoader\&.hpp'\fP
.br
\fC#include 'FilterFactory\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Plugins::Filters::FilterLoader\fP"
.br
.RI "The \fBFilterLoader\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins::Filters\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
