.TH "/home/runner/work/Raytracer/Raytracer/src/Factories/FilterFactory.hpp" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Factories/FilterFactory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IFilterFactory\&.hpp'\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'TFactory\&.hpp'\fP
.br
\fC#include 'FilterHandler\&.hpp'\fP
.br
\fC#include 'IFilter\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Factories::FilterFactory\fP"
.br
.RI "The \fBFilterFactory\fP (singleton factory) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Factories\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
