.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/ICamera.hpp" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/ICamera.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'Transform/Vector2i\&.hpp'\fP
.br
\fC#include 'IDisplayable\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'IFilter\&.hpp'\fP
.br
\fC#include 'ISceneState\&.hpp'\fP
.br
\fC#include 'IEntity\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Entities::ICamera\fP"
.br
.RI "The \fBICamera\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
