.TH "/home/runner/work/Raytracer/Raytracer/src/Display/IDisplayModule.hpp" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Display/IDisplayModule.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Display::IDisplayModule\fP"
.br
.ti -1c
.RI "class \fBRayTracer::Display::IDisplayModule::StartFailed\fP"
.br
.RI "If the function start failed, but it can continue without being completed\&. "
.ti -1c
.RI "class \fBRayTracer::Display::IDisplayModule::EndFailed\fP"
.br
.RI "If the function end failed, but it can continue without being completed\&. "
.ti -1c
.RI "class \fBRayTracer::Display::IDisplayModule::EventFailed\fP"
.br
.RI "If the function event failed, but it can continue without being completed\&. "
.ti -1c
.RI "class \fBRayTracer::Display::IDisplayModule::TickFailed\fP"
.br
.RI "If the function tick failed, but it can continue without being completed\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Display\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
