.TH "/home/runner/work/Raytracer/Raytracer/src/Factories/IEntityFactory.hpp" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Factories/IEntityFactory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'IEntity\&.hpp'\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Factories::IEntityFactory\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Factories\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRayTracer::Factories::IEntityFactory\fP * \fBgetEntityFactoryInstance\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBRayTracer::Factories::IEntityFactory\fP* getEntityFactoryInstance (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
