.TH "/home/runner/work/Raytracer/Raytracer/src/Plugins/Entities/IEntityCreator.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Plugins/Entities/IEntityCreator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'IEntity\&.hpp'\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Plugins::Entities::IEntityCreator\fP"
.br
.RI "The \fBIEntityCreator\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins::Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
