.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/ILight.hpp" 1 "Wed May 10 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/ILight.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Color\&.hpp'\fP
.br
\fC#include 'IDisplayable\&.hpp'\fP
.br
\fC#include 'Transform/Vector3f\&.hpp'\fP
.br
\fC#include 'IEntity\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Entities::ILight\fP"
.br
.RI "The \fBILight\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
