.TH "/home/runner/work/Raytracer/Raytracer/src/Images/Image.hpp" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Images/Image.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Color\&.hpp'\fP
.br
\fC#include 'Vector2i\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Images::Image\fP"
.br
.RI "The \fBImage\fP class\&. "
.ti -1c
.RI "class \fBRayTracer::Images::Image::PixelLine\fP"
.br
.RI "\fBPixelLine\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Images\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
