.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/IMaterial.hpp" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/IMaterial.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Ray\&.hpp'\fP
.br
\fC#include 'Color\&.hpp'\fP
.br
\fC#include 'IDisplayable\&.hpp'\fP
.br
\fC#include 'ITransform\&.hpp'\fP
.br
\fC#include 'Vector3f\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Entities::IMaterial\fP"
.br
.RI "The \fBIMaterial\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
