.TH "/home/runner/work/Raytracer/Raytracer/src/Plugins/Materials/IMaterialCreator.hpp" 1 "Wed May 10 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Plugins/Materials/IMaterialCreator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'IMaterial\&.hpp'\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Plugins::Materials::IMaterialCreator\fP"
.br
.RI "The \fBIMaterialCreator\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins::Materials\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
