.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/IPrimitive.hpp" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/IPrimitive.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <optional>\fP
.br
\fC#include 'Color\&.hpp'\fP
.br
\fC#include 'IDisplayable\&.hpp'\fP
.br
\fC#include 'IEntity\&.hpp'\fP
.br
\fC#include 'IMaterial\&.hpp'\fP
.br
\fC#include 'Ray\&.hpp'\fP
.br
\fC#include 'Vector3f\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Entities::IPrimitive\fP"
.br
.RI "The \fBIPrimitive\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
