.TH "/home/runner/work/Raytracer/Raytracer/src/Scenes/ISetting.hpp" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Scenes/ISetting.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <libconfig\&.h++>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Scenes::ISetting\fP"
.br
.ti -1c
.RI "class \fBRayTracer::Scenes::ISetting::IParsingException\fP"
.br
.RI "an exception for when the key is not found "
.ti -1c
.RI "class \fBRayTracer::Scenes::ISetting::ITypeException\fP"
.br
.RI "an exception for when the key is not found "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Scenes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
