.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/Transform/ITransform.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/Transform/ITransform.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Vector3f\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Entities::Transform::ITransform\fP"
.br
.RI "The \fBITransform\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities::Transform\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
