.TH "/home/runner/work/Raytracer/Raytracer/src/Main.hpp" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Main.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'Parameters\&.hpp'\fP
.br
\fC#include 'Scene\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Main\fP"
.br
.ti -1c
.RI "class \fBRayTracer::Main::MainError\fP"
.br
.ti -1c
.RI "class \fBRayTracer::Main::ArgumentError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcatch_sigint\fP (int sig)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void catch_sigint (int sig)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
