.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/Obj/ObjEntity.hpp" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/Obj/ObjEntity.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'IPrimitive\&.hpp'\fP
.br
\fC#include 'Transform\&.hpp'\fP
.br
\fC#include 'IMaterial\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::PluginsExt::Obj::ObjEntity\fP"
.br
.ti -1c
.RI "class \fBRayTracer::PluginsExt::Obj::ObjEntity::Face\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::Obj\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
