.TH "/home/runner/work/Raytracer/Raytracer/src/Parameters.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Parameters.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Parameters\fP"
.br
.RI "The \fBParameters\fP class singleton\&. "
.ti -1c
.RI "class \fBRayTracer::Parameters::KeyNotFoundError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
