.TH "/home/runner/work/Raytracer/Raytracer/src/Images/PixelThread.hpp" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Images/PixelThread.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IDisplayable\&.hpp'\fP
.br
\fC#include 'Ray\&.hpp'\fP
.br
\fC#include 'Color\&.hpp'\fP
.br
\fC#include <functional>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Images::PixelThread\fP"
.br
.RI "The \fBPixelThread\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Images\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
