.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/Plane/PlaneEntity.hpp" 1 "Wed May 10 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/Plane/PlaneEntity.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'IPrimitive\&.hpp'\fP
.br
\fC#include 'Transform\&.hpp'\fP
.br
\fC#include 'IMaterial\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::PluginsExt::Plane::PlaneEntity\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::Plane\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
