.TH "/home/runner/work/Raytracer/Raytracer/src/Plugins/PluginHandler.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Plugins/PluginHandler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <dlfcn\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Plugins::PluginHandler< Interface, Creator >\fP"
.br
.RI "The \fBPluginHandler\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Plugins\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
