.TH "RayTracer::Plugins::Entities" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Plugins::Entities
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEntityHandler\fP"
.br
.RI "The \fBEntityHandler\fP\&. "
.ti -1c
.RI "class \fBEntityLoader\fP"
.br
.RI "The \fBEntityLoader\fP\&. "
.ti -1c
.RI "class \fBIEntityCreator\fP"
.br
.RI "The \fBIEntityCreator\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
