.TH "RayTracer::PluginsExt::Camera" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt::Camera
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBClustered\fP"
.br
.ti -1c
.RI " \fBFullCustom\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCameraCreator\fP"
.br
.ti -1c
.RI "class \fBCameraEntity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
