.TH "RayTracer::Plugins::PluginLoader< Handler, Interface, Factory >" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Plugins::PluginLoader< Handler, Interface, Factory >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PluginLoader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPluginLoader\fP (const std::string &directory)"
.br
.ti -1c
.RI "void \fBload\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_directory\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Handler , typename Interface , typename Factory > \fBRayTracer::Plugins::PluginLoader\fP< Handler, Interface, Factory >::\fBPluginLoader\fP (const std::string & directory)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename Handler , typename Interface , typename Factory > void \fBRayTracer::Plugins::PluginLoader\fP< Handler, Interface, Factory >::load ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename Handler , typename Interface , typename Factory > std::string \fBRayTracer::Plugins::PluginLoader\fP< Handler, Interface, Factory >::_directory\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
