.TH "RayTracer::Factories::EntityFactory" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Factories::EntityFactory \- The \fBEntityFactory\fP (singleton factory)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntityFactory\&.hpp>\fP
.PP
Inherits \fBRayTracer::Factories::IEntityFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityFactory\fP (const \fBEntityFactory\fP &other)=delete"
.br
.ti -1c
.RI "\fB~EntityFactory\fP ()=default"
.br
.ti -1c
.RI "void \fBadd\fP (const std::string &name, std::unique_ptr< \fBPlugins::Entities::EntityHandler\fP > handler)"
.br
.RI "Add an entity\&. "
.ti -1c
.RI "\fBEntities::IEntity\fP & \fBget\fP (const std::string &name, const \fBScenes::ISetting\fP &setting, \fBILogger\fP &logger) final"
.br
.RI "Get an entity\&. "
.ti -1c
.RI "void \fBclearAll\fP ()"
.br
.RI "Clear all handlers\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEntityFactory\fP & \fBgetInstance\fP ()"
.br
.RI "Get the singleton\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityFactory\fP ()=default"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBTFactory\fP< \fBPlugins::Entities::EntityHandler\fP, \fBEntities::IEntity\fP > & \fBgetFactory\fP ()"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static std::unique_ptr< \fBEntityFactory\fP > \fB_factory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBEntityFactory\fP (singleton factory) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::Factories::EntityFactory::EntityFactory (const \fBEntityFactory\fP & other)\fC [delete]\fP"

.SS "RayTracer::Factories::EntityFactory::~EntityFactory ()\fC [default]\fP"

.SS "RayTracer::Factories::EntityFactory::EntityFactory ()\fC [protected]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void RayTracer::Factories::EntityFactory::add (const std::string & name, std::unique_ptr< \fBPlugins::Entities::EntityHandler\fP > handler)"

.PP
Add an entity\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP the name 
.br
\fIhandler\fP the handler 
.RE
.PP

.SS "void RayTracer::Factories::EntityFactory::clearAll ()"

.PP
Clear all handlers\&. 
.SS "\fBEntities::IEntity\fP& RayTracer::Factories::EntityFactory::get (const std::string & name, const \fBScenes::ISetting\fP & setting, \fBILogger\fP & logger)\fC [final]\fP, \fC [virtual]\fP"

.PP
Get an entity\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP the name 
.br
\fIsetting\fP the setting (to create the entity)
.RE
.PP
\fBReturns\fP
.RS 4
the entity 
.RE
.PP

.PP
Implements \fBRayTracer::Factories::IEntityFactory\fP\&.
.SS "static \fBTFactory\fP<\fBPlugins::Entities::EntityHandler\fP, \fBEntities::IEntity\fP>& RayTracer::Factories::EntityFactory::getFactory ()\fC [static]\fP, \fC [protected]\fP"

.SS "static \fBEntityFactory\fP& RayTracer::Factories::EntityFactory::getInstance ()\fC [static]\fP"

.PP
Get the singleton\&. 
.PP
\fBReturns\fP
.RS 4
the singleton 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "std::unique_ptr<\fBEntityFactory\fP> RayTracer::Factories::EntityFactory::_factory\fC [static]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
