.TH "RayTracer::Parameters::KeyNotFoundError" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Parameters::KeyNotFoundError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parameters\&.hpp>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyNotFoundError\fP (const std::string &key)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_key\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::Parameters::KeyNotFoundError::KeyNotFoundError (const std::string & key)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char* RayTracer::Parameters::KeyNotFoundError::what () const\fC [override]\fP, \fC [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string RayTracer::Parameters::KeyNotFoundError::_key\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
