.TH "RayTracer::Plugins::Filters" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Plugins::Filters
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFilterHandler\fP"
.br
.RI "The \fBFilterHandler\fP\&. "
.ti -1c
.RI "class \fBFilterLoader\fP"
.br
.RI "The \fBFilterLoader\fP\&. "
.ti -1c
.RI "class \fBIFilterCreator\fP"
.br
.RI "The \fBIFilterCreator\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
