.TH "RayTracer::Main::MainError" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Main::MainError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Main\&.hpp>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainError\fP (const std::string &message)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_message\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::Main::MainError::MainError (const std::string & message)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char* RayTracer::Main::MainError::what () const\fC [override]\fP, \fC [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string RayTracer::Main::MainError::_message\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
