.TH "RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter" 1 "Wed May 10 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SSAAx4Filter\&.hpp>\fP
.PP
Inherits \fBRayTracer::Filters::IFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSSAAx4Filter\fP (const \fBScenes::ISetting\fP &config, \fBILogger\fP &logger)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBImages::Image\fP &image) final"
.br
.RI "Apply the filter on an image\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBwaitOnePlace\fP ()"
.br
.RI "Wait one place in the vector of futures\&. "
.ti -1c
.RI "void \fBwaitAllFinisehd\fP ()"
.br
.RI "Wait all places in the vector of futures\&. "
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static \fBImages::Color\fP \fBgetColorsMean\fP (const std::vector< \fBImages::Color\fP > &colors)"
.br
.RI "Mean of the colors\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBILogger\fP & \fB_logger\fP"
.br
.ti -1c
.RI "int \fB_maxThread\fP"
.br
.ti -1c
.RI "std::vector< std::future< void > > \fB_futures\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::SSAAx4Filter (const \fBScenes::ISetting\fP & config, \fBILogger\fP & logger)"

.SH "Member Function Documentation"
.PP 
.SS "void RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::apply (\fBImages::Image\fP & image)\fC [final]\fP, \fC [virtual]\fP"

.PP
Apply the filter on an image\&. 
.PP
\fBParameters\fP
.RS 4
\fIimage\fP the image 
.RE
.PP

.PP
Implements \fBRayTracer::Filters::IFilter\fP\&.
.SS "static \fBImages::Color\fP RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::getColorsMean (const std::vector< \fBImages::Color\fP > & colors)\fC [static]\fP, \fC [private]\fP"

.PP
Mean of the colors\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolors\fP The colors to mean
.RE
.PP
\fBReturns\fP
.RS 4
The mean 
.RE
.PP

.SS "void RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::waitAllFinisehd ()\fC [private]\fP"

.PP
Wait all places in the vector of futures\&. 
.SS "void RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::waitOnePlace ()\fC [private]\fP"

.PP
Wait one place in the vector of futures\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::future<void> > RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::_futures\fC [private]\fP"

.SS "\fBILogger\fP& RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::_logger\fC [private]\fP"

.SS "int RayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter::_maxThread\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
