.TH "RayTracer::Scenes::ConfigWrapper::ReadException" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Scenes::ConfigWrapper::ReadException \- an exception for when the file can't be read  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConfigWrapper\&.hpp>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadException\fP (const std::string &message)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const  throw ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_message\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
an exception for when the file can't be read 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::Scenes::ConfigWrapper::ReadException::ReadException (const std::string & message)"

.SH "Member Function Documentation"
.PP 
.SS "const char* RayTracer::Scenes::ConfigWrapper::ReadException::what () const"

.SH "Member Data Documentation"
.PP 
.SS "std::string RayTracer::Scenes::ConfigWrapper::ReadException::_message\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
