.TH "RayTracer::PluginsExt::AntiAliasing::SSAAx4" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt::AntiAliasing::SSAAx4
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSSAAx4Creator\fP"
.br
.ti -1c
.RI "class \fBSSAAx4Filter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
