.TH "RayTracer::Images" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Images
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColor\fP"
.br
.RI "The \fBColor\fP class\&. "
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "The \fBImage\fP class\&. "
.ti -1c
.RI "class \fBImagePipeLine\fP"
.br
.RI "The \fBImagePipeLine\fP class\&. "
.ti -1c
.RI "class \fBIRayIterator\fP"
.br
.RI "The RayIterator class\&. "
.ti -1c
.RI "class \fBPixelThread\fP"
.br
.RI "The \fBPixelThread\fP class\&. "
.ti -1c
.RI "class \fBRay\fP"
.br
.RI "The \fBRay\fP class\&. "
.ti -1c
.RI "class \fBRayIterrator\fP"
.br
.RI "The \fBRayIterrator\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
