.TH "RayTracer::PluginsExt" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAmbientLight\fP"
.br
.ti -1c
.RI " \fBAntiAliasing\fP"
.br
.ti -1c
.RI " \fBBlackAndWhite\fP"
.br
.ti -1c
.RI " \fBCamera\fP"
.br
.ti -1c
.RI " \fBChessBoard\fP"
.br
.ti -1c
.RI " \fBCone\fP"
.br
.ti -1c
.RI " \fBCylinder\fP"
.br
.ti -1c
.RI " \fBDisk\fP"
.br
.ti -1c
.RI " \fBLimitedCone\fP"
.br
.ti -1c
.RI " \fBLimitedCylinder\fP"
.br
.ti -1c
.RI " \fBLimitedPlane\fP"
.br
.ti -1c
.RI " \fBMirror\fP"
.br
.ti -1c
.RI " \fBObj\fP"
.br
.ti -1c
.RI " \fBPlainMaterial\fP"
.br
.ti -1c
.RI " \fBPlane\fP"
.br
.ti -1c
.RI " \fBPointLight\fP"
.br
.ti -1c
.RI " \fBRefraction\fP"
.br
.ti -1c
.RI " \fBSphere\fP"
.br
.ti -1c
.RI " \fBSpotLight\fP"
.br
.ti -1c
.RI " \fBTorus\fP"
.br
.ti -1c
.RI " \fBTransparency\fP"
.br
.ti -1c
.RI " \fBTriangle\fP"
.br
.ti -1c
.RI " \fBZebra\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
