.TH "RayTracer::PluginsExt::Transparency" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt::Transparency
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransparencyCreator\fP"
.br
.ti -1c
.RI "class \fBTransparencyMaterial\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
