.TH "RayTracer::Scenes::ISetting::ITypeException" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Scenes::ISetting::ITypeException \- an exception for when the key is not found  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ISetting\&.hpp>\fP
.PP
Inherits std::exception\&.
.PP
Inherited by \fBRayTracer::Scenes::SettingWrapper::TypeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ITypeException\fP ()=default"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const override=0  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
an exception for when the key is not found 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual RayTracer::Scenes::ISetting::ITypeException::~ITypeException ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual const char* RayTracer::Scenes::ISetting::ITypeException::what () const\fC [override]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBRayTracer::Scenes::SettingWrapper::TypeException\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
