.TH "RayTracer::PluginsExt::Zebra::ZebraMaterial" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt::Zebra::ZebraMaterial
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ZebraMaterial\&.hpp>\fP
.PP
Inherits \fBRayTracer::Entities::IMaterial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZebraMaterial\fP (const \fBScenes::ISetting\fP &config)"
.br
.ti -1c
.RI "\fBImages::Color\fP \fBgetColor\fP (const \fBImages::Ray\fP &ray, const \fBEntities::Transform::ITransform\fP &centerObj, const \fBEntities::Transform::Vector3f\fP &intersect, const \fBScenes::IDisplayable\fP &displayable) const final"
.br
.RI "Get the color\&. "
.ti -1c
.RI "void \fBsetColor\fP (const \fBImages::Color\fP &color) final"
.br
.RI "Set the color\&. "
.ti -1c
.RI "\fBImages::Color\fP \fBredirectionLight\fP (const \fBImages::Ray\fP &ray, const \fBScenes::IDisplayable\fP &displayable, const \fBEntities::Transform::Vector3f\fP &intersect) const final"
.br
.RI "this function is called when the object intercept the ray light "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBEntities::Transform::Vector3f\fP \fB_ambient\fP"
.br
.ti -1c
.RI "\fBEntities::Transform::Vector3f\fP \fB_diffuse\fP"
.br
.ti -1c
.RI "\fBEntities::Transform::Vector3f\fP \fB_specular\fP"
.br
.ti -1c
.RI "double \fB_shininess\fP"
.br
.ti -1c
.RI "\fBImages::Color\fP \fB_pair\fP"
.br
.ti -1c
.RI "\fBImages::Color\fP \fB_impair\fP"
.br
.ti -1c
.RI "double \fB_size\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::PluginsExt::Zebra::ZebraMaterial::ZebraMaterial (const \fBScenes::ISetting\fP & config)"

.SH "Member Function Documentation"
.PP 
.SS "\fBImages::Color\fP RayTracer::PluginsExt::Zebra::ZebraMaterial::getColor (const \fBImages::Ray\fP & ray, const \fBEntities::Transform::ITransform\fP & centerObj, const \fBEntities::Transform::Vector3f\fP & intersect, const \fBScenes::IDisplayable\fP & displayable) const\fC [final]\fP, \fC [virtual]\fP"

.PP
Get the color\&. 
.PP
\fBParameters\fP
.RS 4
\fIcenterObj\fP the center of the object impacted 
.br
\fIintersect\fP the intersection point on the object 
.br
\fIdisplayable\fP the displayable objects
.RE
.PP
\fBReturns\fP
.RS 4
the color 
.RE
.PP

.PP
Implements \fBRayTracer::Entities::IMaterial\fP\&.
.SS "\fBImages::Color\fP RayTracer::PluginsExt::Zebra::ZebraMaterial::redirectionLight (const \fBImages::Ray\fP & ray, const \fBScenes::IDisplayable\fP & displayable, const \fBEntities::Transform::Vector3f\fP & intersect) const\fC [final]\fP, \fC [virtual]\fP"

.PP
this function is called when the object intercept the ray light 
.PP
\fBParameters\fP
.RS 4
\fIray\fP the ray between the light and the object 
.br
\fIdisplayable\fP the displayable 
.br
\fIintersect\fP the intersection point between this point and the ray
.RE
.PP
\fBReturns\fP
.RS 4
the color of the shadow 
.RE
.PP

.PP
Implements \fBRayTracer::Entities::IMaterial\fP\&.
.SS "void RayTracer::PluginsExt::Zebra::ZebraMaterial::setColor (const \fBImages::Color\fP & color)\fC [final]\fP, \fC [virtual]\fP"

.PP
Set the color\&. 
.PP
\fBParameters\fP
.RS 4
\fIcolor\fP the color 
.RE
.PP

.PP
Implements \fBRayTracer::Entities::IMaterial\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEntities::Transform::Vector3f\fP RayTracer::PluginsExt::Zebra::ZebraMaterial::_ambient\fC [private]\fP"

.SS "\fBEntities::Transform::Vector3f\fP RayTracer::PluginsExt::Zebra::ZebraMaterial::_diffuse\fC [private]\fP"

.SS "\fBImages::Color\fP RayTracer::PluginsExt::Zebra::ZebraMaterial::_impair\fC [private]\fP"

.SS "\fBImages::Color\fP RayTracer::PluginsExt::Zebra::ZebraMaterial::_pair\fC [private]\fP"

.SS "double RayTracer::PluginsExt::Zebra::ZebraMaterial::_shininess\fC [private]\fP"

.SS "double RayTracer::PluginsExt::Zebra::ZebraMaterial::_size\fC [private]\fP"

.SS "\fBEntities::Transform::Vector3f\fP RayTracer::PluginsExt::Zebra::ZebraMaterial::_specular\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
