.TH "RayTracer::Entities::Transform" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Entities::Transform
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBITransform\fP"
.br
.RI "The \fBITransform\fP class\&. "
.ti -1c
.RI "class \fBTransform\fP"
.br
.RI "The \fBTransform\fP class\&. "
.ti -1c
.RI "class \fBVector2i\fP"
.br
.RI "The \fBVector2i\fP class\&. "
.ti -1c
.RI "class \fBVector3f\fP"
.br
.RI "The \fBVector3f\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
