.TH "RayTracer::Plugins::Materials" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Plugins::Materials
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIMaterialCreator\fP"
.br
.RI "The \fBIMaterialCreator\fP class\&. "
.ti -1c
.RI "class \fBMaterialHandler\fP"
.br
.RI "The \fBMaterialHandler\fP\&. "
.ti -1c
.RI "class \fBMaterialLoader\fP"
.br
.RI "The \fBMaterialLoader\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
