.TH "RayTracer::PluginsExt" 1 "Wed May 10 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAmbientLight\fP"
.br
.ti -1c
.RI " \fBAntiAliasing\fP"
.br
.ti -1c
.RI " \fBCamera\fP"
.br
.ti -1c
.RI " \fBCone\fP"
.br
.ti -1c
.RI " \fBCylinder\fP"
.br
.ti -1c
.RI " \fBDisk\fP"
.br
.ti -1c
.RI " \fBLimitedCone\fP"
.br
.ti -1c
.RI " \fBLimitedCylinder\fP"
.br
.ti -1c
.RI " \fBLimitedPlane\fP"
.br
.ti -1c
.RI " \fBPlainMaterial\fP"
.br
.ti -1c
.RI " \fBPlane\fP"
.br
.ti -1c
.RI " \fBPointLight\fP"
.br
.ti -1c
.RI " \fBSphere\fP"
.br
.ti -1c
.RI " \fBSpotLight\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
