.TH "RayTracer::Scenes::SceneLoader::BadFileError" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Scenes::SceneLoader::BadFileError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SceneLoader\&.hpp>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadFileError\fP (const std::string &error)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const override  throw ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_error\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::Scenes::SceneLoader::BadFileError::BadFileError (const std::string & error)"

.SH "Member Function Documentation"
.PP 
.SS "const char* RayTracer::Scenes::SceneLoader::BadFileError::what () const\fC [override]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string RayTracer::Scenes::SceneLoader::BadFileError::_error\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
