.TH "RayTracer::PluginsExt::Camera::Clustered" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::PluginsExt::Camera::Clustered
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCameraClusterCreator\fP"
.br
.ti -1c
.RI "class \fBCameraClusterEntity\fP"
.br
.ti -1c
.RI "class \fBClusterRayIterator\fP"
.br
.RI "The \fBClusterRayIterator\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
