.TH "RayTracer" 1 "Fri May 26 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDisplay\fP"
.br
.ti -1c
.RI " \fBEntities\fP"
.br
.ti -1c
.RI " \fBFactories\fP"
.br
.ti -1c
.RI " \fBFilters\fP"
.br
.ti -1c
.RI " \fBImages\fP"
.br
.ti -1c
.RI " \fBPlugins\fP"
.br
.ti -1c
.RI " \fBPluginsExt\fP"
.br
.ti -1c
.RI " \fBScenes\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBILogger\fP"
.br
.RI "\fBLogger\fP singleton\&. "
.ti -1c
.RI "class \fBLogger\fP"
.br
.RI "\fBLogger\fP singleton\&. "
.ti -1c
.RI "class \fBMain\fP"
.br
.ti -1c
.RI "class \fBParameters\fP"
.br
.RI "The \fBParameters\fP class singleton\&. "
.ti -1c
.RI "class \fBProgress\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
