.TH "RayTracer::Scenes::Displayable::DisplayableException" 1 "Sat May 13 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Scenes::Displayable::DisplayableException \- an exception for when the key is not found  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Displayable\&.hpp>\fP
.PP
Inherits \fBRayTracer::Scenes::IDisplayable::IDisplayableException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplayableException\fP (const std::string &key)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const final  throw ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_msg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
an exception for when the key is not found 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RayTracer::Scenes::Displayable::DisplayableException::DisplayableException (const std::string & key)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char* RayTracer::Scenes::Displayable::DisplayableException::what () const\fC [final]\fP, \fC [virtual]\fP"

.PP
Implements \fBRayTracer::Scenes::IDisplayable::IDisplayableException\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string RayTracer::Scenes::Displayable::DisplayableException::_msg\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
