.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/RefractionMaterial/RefractionMaterial.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/RefractionMaterial/RefractionMaterial.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ISetting\&.hpp'\fP
.br
\fC#include 'Ray\&.hpp'\fP
.br
\fC#include 'Color\&.hpp'\fP
.br
\fC#include 'ITransform\&.hpp'\fP
.br
\fC#include 'Vector3f\&.hpp'\fP
.br
\fC#include 'IMaterial\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::PluginsExt::Refraction::RefractionMaterial\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::Refraction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
