.TH "/home/runner/work/Raytracer/Raytracer/src/Scenes/SceneLoader.hpp" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Scenes/SceneLoader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include <string>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <map>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'FilterLoader\&.hpp'\fP
.br
\fC#include 'EntityLoader\&.hpp'\fP
.br
\fC#include 'MaterialLoader\&.hpp'\fP
.br
\fC#include 'ConfigWrapper\&.hpp'\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Scenes::SceneLoader\fP"
.br
.RI "The \fBSceneLoader\fP class\&. "
.ti -1c
.RI "class \fBRayTracer::Scenes::SceneLoader::BadFileError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Scenes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
