.TH "/home/runner/work/Raytracer/Raytracer/src/Scenes/Scene.hpp" 1 "Sun May 14 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Scenes/Scene.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <future>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br
\fC#include 'ICamera\&.hpp'\fP
.br
\fC#include 'ILight\&.hpp'\fP
.br
\fC#include 'IPrimitive\&.hpp'\fP
.br
\fC#include 'SceneState\&.hpp'\fP
.br
\fC#include 'Displayable\&.hpp'\fP
.br
\fC#include 'EntityFactory\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Scenes::Scene\fP"
.br
.RI "The \fBScene\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Scenes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
