.TH "/home/runner/work/Raytracer/Raytracer/src/Scenes/SettingWrapper.hpp" 1 "Fri May 12 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Scenes/SettingWrapper.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <libconfig\&.h++>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <exception>\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Scenes::SettingWrapper\fP"
.br
.RI "The \fBSettingWrapper\fP class\&. "
.ti -1c
.RI "class \fBRayTracer::Scenes::SettingWrapper::ParsingException\fP"
.br
.RI "an exception for when the key is not found "
.ti -1c
.RI "class \fBRayTracer::Scenes::SettingWrapper::TypeException\fP"
.br
.RI "an exception for when the key is not found "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Scenes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
