.TH "/home/runner/work/Raytracer/Raytracer/PluginsExt/AntiAliasing/SSAAx4/SSAAx4Filter.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/PluginsExt/AntiAliasing/SSAAx4/SSAAx4Filter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <future>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Color\&.hpp'\fP
.br
\fC#include 'ILogger\&.hpp'\fP
.br
\fC#include 'IFilter\&.hpp'\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br
\fC#include 'Image\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::PluginsExt::AntiAliasing::SSAAx4::SSAAx4Filter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::AntiAliasing\fP"
.br
.ti -1c
.RI " \fBRayTracer::PluginsExt::AntiAliasing::SSAAx4\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
