.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/Transform/Vector2i.hpp" 1 "Thu May 11 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/Transform/Vector2i.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include 'IConfig\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Entities::Transform::Vector2i\fP"
.br
.RI "The \fBVector2i\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities::Transform\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBRayTracer::Entities::Transform::Vector2i\fP &vector)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBRayTracer::Entities::Transform::Vector2i\fP & vector)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
