.TH "/home/runner/work/Raytracer/Raytracer/src/Entities/Transform/Vector3f.hpp" 1 "Tue May 16 2023" "RayTracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/Raytracer/Raytracer/src/Entities/Transform/Vector3f.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include 'ISetting\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRayTracer::Entities::Transform::Vector3f\fP"
.br
.RI "The \fBVector3f\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRayTracer\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities\fP"
.br
.ti -1c
.RI " \fBRayTracer::Entities::Transform\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBRayTracer::Entities::Transform::Vector3f\fP &vector)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBRayTracer::Entities::Transform::Vector3f\fP & vector)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RayTracer from the source code\&.
