name: Publish

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-OOP-400-TLS-4-1-raytracer-xavier.mitault.git
  BINARY: "raytracer"

jobs:
  compil:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v2

    - name: install libconfig
      run: sudo dnf install -y libconfig-devel libconfig

    - name: make
      run: |
        mkdir -p build
        cd build || exit 1
        timeout 2m cmake .. || exit 2
        timeout 2m make || exit 3

    - name: check binary
      run: |
        cd build || exit 1
        if [[ ! -f $BINARY ]]; then
          echo "::error title=Executable not found::$BINARY"
        fi

  publish:
    needs: [compil]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.SSH_KEY }}
