name: Build and release

on:
  push:
    tags:
      - '*'

jobs:

  release-exe:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y tar gzip libconfig-devel libconfig

      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: make -j

      - name: Package to archive (binary)
        run: |
          mkdir raytracer-bin
          cp raytracer raytracer-bin/raytracer
          cp -r plugins raytracer-bin/
          tar -czf - raytracer-bin | gzip -9 > raytracer.tar.gz

      - name: Upload to release (binary)
        uses: actions/upload-artifact@v3
        with:
          name: raytracer.tar.gz
          path: raytracer.tar.gz

      - name: Package to archive (examples)
        run: |
          mkdir raytracer-examples
          cp scenes/**/*.yaax scenes/*.yaax raytracer-examples/
          find raytracer-examples -name '*.yaax' -type f -print -exec ./raytracer --scene-path {} --output-path {} \;
          tar -czf - raytracer-examples | gzip -9 > raytracer-examples.tar.gz

      - name: Upload to release (examples)
        uses: actions/upload-artifact@v3
        with:
          name: raytracer-examples.tar.gz
          path: raytracer-examples.tar.gz
